#include<stdio.h>
int main()
{
    int i,j,arr[100][100],sum1=0,sum2=0,max1=0,max=0,m,n;
    scanf("%d%d",&n,&m);
    for(i=0;i<n;i++)
    {
        for(j=0;j<m;j++)
        {
            scanf("%d",&arr[i][j]);
        }
    }
    for(i=0;i<n;i++)
    {
        sum1=0;
        for(j=0;j<m;j++)
        {
            sum1=sum1+arr[i][j];
        }
        if(max<sum1)
        {
            max=sum1;
        }
    }
    for(j=0;j<m;j++)
    {
        sum2=0;
        for(i=0;i<n;i++)
        {
            sum2=sum2+arr[i][j];
        }
        if(max1<sum2)
        {
            max1=sum2;
        }
    }
    if(max>max1)
    {
        printf("%d",max);
    }
    else
    {
        printf("%d",max1);
    }
}